trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'AnyCPU'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/backdoor.sln'

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'serviceConnection-APIToken-User'
    appSlug: 'v-mimary-microsoft.com/xam-android-backdoor'
    appFile: '$(build.binariesDirectory)/$(buildConfiguration)/*.apk'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    destinationType: 'groups'

- task: CopyFiles@2
  displayName: 'copy the tools folder because wild cards seem to fail on the tools'
  inputs:
    Contents: '_buildOutput/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact drop-android'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop-mmc'