trigger:
- master

jobs:
 
- job: Android
  displayName: "job android"
  pool:
    name: Hosted Windows 2019 with VS2019

  variables:
    solution: '**/backdoor.sln'
    buildPlatform: 'x86|x64|ARM'
    buildConfiguration: 'Release'
    varOutputDirectory: '$(build.binariesdirectory)/$(buildConfiguration)'

  steps:

  - task: NuGetToolInstaller@1
    displayName: 'Install nuget'
    inputs:
      versionSpec: '5.3.0'

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
    
  - task: XamarinAndroid@1
    displayName: "build android"
    inputs:
      projectFile: '**/backdoor.Droid.csproj'
      outputDirectory: '$(varOutputDirectory)'
      configuration: '$(buildConfiguration)'
      msbuildArchitectureOption: x64
      jdkOption: 'JDKVersion'

  # let's build all the tests so we can run them in AppCenter
  - task: MSBuild@1
    displayName: 'Build all Tests-csproj files'
    inputs:      
      solution: "**/*Tests.csproj"
      configuration: '$(buildConfiguration)'
      msbuildArguments: '/p:OutputPath="$(varOutputDirectory)/test-assembly"'
   
    # I just check APK
  - task: AndroidSigning@2
    displayName: "align and sign"  
    inputs:
      apkFiles: '$(varOutputDirectory)/*.apk'
      jarsign: false

  # - task: CopyFiles@2
  #   displayName: 'Copy files'
  #   inputs:
  #     SourceFolder: '$(build.sourcesdirectory)'
  #     Contents: '**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'
  #     TargetFolder: '$(varOutputDirectory)/temp-1'

  # - task: CopyFiles@2
  #   displayName: 'Copy 3'
  #   inputs:
  #     sourceFolder: '$(varOutputDirectory)/test-assembly'
  #     contents: '**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'
  #     targetFolder: '$(varOutputDirectory)/temp-2'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(varOutputDirectory)'

  - task: CopyFiles@2
    displayName: 'copy the tools folder because wild cards seem to fail on the tools'
    inputs:
      Contents: '**/Xamarin.UITest.*/**'
      SourceFolder: '$(build.sourcesdirectory)/packages'
      TargetFolder: '$(build.sourcesdirectory)/tools'
      flattenFolders: true
      
  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: 'serviceConnection-APIToken-User'
      appSlug: 'v-mimary-microsoft.com/xam-android-backdoor'
      appFile: '$(varOutputDirectory)/*.apk'
      symbolsOption: 'Android'
      releaseNotesOption: 'input'
      destinationType: 'groups'
      isSilent: true