trigger:
- master

jobs:
 
- job: Android
  displayName: "job android"
  pool:
    name: Hosted Windows 2019 with VS2019

  variables:
    solution: '**/backdoor.sln'
    buildPlatform: 'x86|x64|ARM'
    buildConfiguration: 'Release'

  steps:

  - task: NuGetToolInstaller@1
    displayName: 'Install nuget'
    inputs:
      versionSpec: '5.3.0'

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
    
  - task: XamarinAndroid@1
    displayName: "build android"
    inputs:
      projectFile: '**/backdoor.Droid.csproj'
      outputDirectory: '$(build.ArtifactStagingDirectory)/$(buildConfiguration)'
      configuration: '$(buildConfiguration)'
      msbuildArchitectureOption: x64
      jdkOption: 'JDKVersion'

    # I just check APK
  - task: AndroidSigning@2
    displayName: "align and sign"  
    inputs:
      apkFiles: '$(build.ArtifactStagingDirectory)/$(buildConfiguration)/*.apk'
      jarsign: false

  # let's build all the tests so we can run them in AppCenter
  - task: MSBuild@1
    displayName: 'Build all Tests-csproj files'
    inputs:      
      solution: "**/*Tests.csproj"
      configuration: '$(buildConfiguration)'
      msbuildArguments: '/p:OutputPath="$(build.ArtifactStagingDirectory)/$(BuildConfiguration)/test-assembly"'
   
  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**'
      TargetFolder: '$(build.artifactstagingdirectory)/$(buildConfiguration)'
      flattenFolders: true

  - task: CopyFiles@2
    displayName: 'Copy 3'
    inputs:
      sourceFolder: '$(build.ArtifactStagingDirectory)/$(buildConfiguration)/test-assembly'
      contents: '**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/$(buildConfiguration)'
