trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:    
    projectFile: '**/*.Droid.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'copy the tools folder because wild cards seem to fail on the tools'
  inputs:
    Contents: '_buildOutput/**'
    targetFolder: $(outputDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact drop-android'
  inputs:
    PathtoPublish: '$(outputDirectory)'
    ArtifactName: 'drop-mmc'